### ISSUE TITLE
Import error on sassd

### ISSUE THREAD

**Issue by rightisleft** [oddrationale/dart_libsass#9]
After following the instructions on the home page, and getting the binaries compiled, attempting to feed a valid scss file into the parser fails:

```
➜  dart_libsass git:(master) ✗ cat bin/input.scss 
section {
    background-color: red;
}%
➜  dart_libsass git:(master) ✗ dart bin/sassd.dart bin/input.scss bin/ouput.scss
Cannot find initialization function in extension'package:libsass/libsass.dart': error: line 10 pos 1: library handler failed
import 'dart-ext:sass_extension';
^
```

Directory Structures

package root:
http://pastebin.com/FwYEza7w

libsass:
http://pastebin.com/HinhEM6i

➜  dart_libsass git:(master) ✗ dart --version
Dart VM version: 1.13.0-dev.2.0 (Tue Sep  8 05:13:39 2015) on "macos_x64"

**Comment by oddrationale** [comment]
Hey, Jack!

Thanks for the bug report. I haven't tested the code with the latest version of Dart. But I'll try to get to that when I have time.

Best,
Dariel Dato-on

**Comment by rightisleft** [comment]
Any updates on this?

**Comment by oddrationale** [comment]
I'll be working on updating this package over the holidays. Sorry for the delay.

I don't have a Mac, so I've never tested it on MacOS. But it sounds like there's an issue with the compilation.

Can you try compiling the extension with the old [`tool/build.sh`](https://raw.githubusercontent.com/oddrationale/dart_libsass/049a462ae0b06ffb57fdae96270d49fdf7b4e11f/tool/build.sh) script instead of the `tool/build.dart`? First, clean up the old build files, e.g.  `rm lib/src/libsass/lib/libsass.a` and `rm lib/src/libsass/*.o`. Then download a copy of the shell script into the tool directory and run `./tool/build.sh`.

It could be that the dart version of the build script does not compile it correctly.

Let me know!

**Comment by oddrationale** [comment]
Also, in order to try the build.sh script, you'll need to uncomment lines 47-51.

**Comment by oddrationale** [comment]
Got home and started looking into this. Ignore my previous two comments. It is not a problem with compiling on Mac. There's been some api changes with how extensions are loaded. 

https://codereview.chromium.org/186473003/#ps40001

I'll troubleshoot and fix the extension to work with the new version.

**Comment by oddrationale** [comment]
I fixed the build script which was causing the issue. I tested it on my machine (Linux) and it is working again. Please re-open if you are still having the same error message on Mac. Thanks!
